### ISSUE TITLE
addon-administration 1.6 does not work with {auth,resource}-server 2.3

### ISSUE THREAD

**Issue by mirabilos** [osiam/addon-administration#116]
I get an error message (full stack trace is confidential but has been known)…

    org.osiam.client.exception.OsiamClientException: Unable to deserialize search result

… when I login to addon-administration and click Authorise.

**Comment by tkrille** [comment]
Hello @mirabilos,

you need to update your version of the addon-administration to 1.7. Only version 1.7 is compatible with OSIAM 2.4. Add-on are generally only known to work with the version of OSIAM that they're bundled with. They might work with lower or newer versions, but there's no guarantee. I've updated the release notes to reflect this.
