### ISSUE TITLE
Changing the displayName removes all members from a group

### ISSUE THREAD

**Issue by wallner** [osiam/addon-administration#119]
In osiam/osiam#95 @xaviarias filed an issue that using addon-administration the members of a group get lost when the `displayName` of a group is changed. This is a bug in this component here, therefore we close it there and track the bug in this issure.

**Comment by facundofarias** [comment]
In which version is this solved? v1.9?
Thanks!

**Comment by dacrome** [comment]
It's not released yet. But we will release the `addon-administration` in the next 2 weeks.

**Comment by facundofarias** [comment]
Hi @dacrome! 
Is the addon-administration already released? Does it work with OSIAM 2.5?
Thanks

**Comment by dacrome** [comment]
Hi @facundofarias,

> Is the addon-administration already released?

you can try the official pre-release of 1.9: https://dl.bintray.com/osiam/downloads/addon-administration/1.9.CR3/.

> Does it work with OSIAM 2.5?

Yes.

Greetz,
David
