### ISSUE TITLE
Long labels of attributes overshadowed by the corresponding input field

### ISSUE THREAD

**Issue by ckoeni** [osiam/addon-administration#45]
As a feature request i like to propose implementing wordwrap for the OSIAM administration. This is useful for long labels of attributes, because the input field overshadows the label and the full information of the label is lost/not available to the user.

**Comment by tkrille** [comment]
Hello @ckoeni,

I am currently unable to understand your issue. Can you please clarify? If this is a UI thing, it would be nice if you make some screenshots.

**Comment by dacrome** [comment]
thanks for your issue, but this repository will be archived.
