### ISSUE TITLE
Saving of users (type of multivalues)

### ISSUE THREAD

**Issue by smancke** [osiam/addon-administration#50]
When I edit a user, which was created by the registration of the addon-self-administration, I can not save the user, because the email address the administration requires the mail address to have a type.
When I insert a type (any text), I get the following error message: 
"Exception: The value of org.osiam.resources.scim.Address$Type can't be null or empty.  [...]"

The same problem my occur with other multivalued types like e.g. the address.

**Comment by dacrome** [comment]
Fixed with https://github.com/osiam/addon-administration/pull/55
