### ISSUE TITLE
Strange attributes of OAuth client 

### ISSUE THREAD

**Issue by tkrille** [osiam/addon-administration#61]
The OAuth client has some strange attributes, like `accesstokenvalidityseconds=2342`. It's also not configured for implicit approval, but it should be as it is an internal, trusted client. Last bot not least, it declares grants that it doesn't use. We should fix all these issues.

**Comment by dacrome** [comment]
Thanks for this issue and your already created PR https://github.com/osiam/addon-administration/pull/62. :+1:
