### ISSUE TITLE
Create a landingpage

### ISSUE THREAD

**Issue by tkrille** [osiam/addon-administration#64]
Currently if a user accesses the administration UI and is not logged in, they will be redirected to start the 3-legged OAuth flow. This is somewhat confusing when one tries to logout, as OSIAM realizes a single sign-on. This has the effect that after clicking on logout one will see the list of users again. A landingpage that tells the user that they are not logged in and requests them to explicitly login would solve this issue.

**Comment by dacrome** [comment]
The logout would destroy the administration session (and remove the [`GeneralSessionData`](https://github.com/osiam/addon-administration/blob/4f0bdcbe5d7047fce66a7be2739ddda41bd1111b/src/main/java/org/osiam/addons/administration/model/session/GeneralSessionData.java) from the current session) and that's how the administration can differ between the login status and show the landingpage?

**Comment by tkrille** [comment]
Yes, that's the idea.

**Comment by facundofarias** [comment]
Hi all,
In which version will be this released? We have OSIAM Server 2.5, and the bug is still present.
Thanks!

**Comment by dacrome** [comment]
Hi @facundofarias.

What do you mean with OSIAM server 2.5? The [docker-image](https://github.com/osiam/docker-image)? Or do you have a OSIAM server 2.5 installation and using the [addon-administration 1.8](https://github.com/osiam/addon-administration/releases/tag/v1.8)?

Currently we put all efforts in OSIAM 3.0, but we discuss to release the addons ([self-administration](https://github.com/osiam/addon-self-administration) and [administration](https://github.com/osiam/addon-administration)) before we release OSIAM 3.0. If so, we will release it before end of April. I give you a feedback if we decided how to deal with it.

Regards,
David

**Comment by facundofarias** [comment]
Hi @dacrome,

We have OSIAM Server 2.5, and addon-administration 1.8, as you said.
Will the addons work with OSIAM Server 2.5? Or shall we update everything? (We already have it in production :) )

Thanks!

**Comment by dacrome** [comment]
Hey @facundofarias.

> We already have it in production :)

I'm happy to hear that :)

> Will the addons work with OSIAM Server 2.5? Or shall we update everything?

For sure it would be nice if you update to OSIAM 3.0, but the addons also work with OSIAM server 2.5.

**Comment by tkrille** [comment]
Hello @facundofarias,

you can now try the official pre-release of 1.9: https://dl.bintray.com/osiam/downloads/addon-administration/1.9.CR2/
