### ISSUE TITLE
All selenium tests are failing

### ISSUE THREAD

**Issue by dacrome** [osiam/addon-administration#66]
Disregard the horrible fact that the selenium tests of this addon need the started [osiam integration tests](https://github.com/osiam/connector4java-integration-tests), all selenium tests are failing because they are trying to access html elements which are not present in the current html templates. Example exception message:
`org.openqa.selenium.NoSuchElementException: Unable to locate a node using //form[@id = 'confirmation-form']/button`

**Comment by dacrome** [comment]
I'm on the way to [fix the selenium tests + run the OSIAM backend as a docker container](https://github.com/osiam/addon-administration/compare/master...dacrome:fix-selenium-tests?expand=1) to get rid of an external started auth- and resource-server. It is like I already described, the selenium tests try to access html elements which are not existing anymore. So the tests are not updated with the changed html. Is it worth to work on fixing the selenium tests or should we completely rewrite them from scratch?

**Comment by dacrome** [comment]
I don't think it's worth fixing the selenium tests. My suggestion is to remove selenium and introduce http://www.gebish.org/. I can think of creating a user after a successful 3-legged flow as a first test.

**Comment by tkrille** [comment]
Alright, let's go for Geb.
