### ISSUE TITLE
Selecting "All Results per page" still pages the list

### ISSUE THREAD

**Issue by tkrille** [osiam/addon-administration#71]
The administration seems to not page the user list correctly. I always get 100 users at max. I assume that's also the case for the group list, but didn't test it.

Steps to reproduce:
1. Put more than 100 users in the database
2. Select "All" in the combobox labeled with "Results per page" below the user list

Expected:
A list with all users shown.

Actual:
A list that only show 100 users and pages the results.

**Comment by dacrome** [comment]
thanks for your issue, but this repository will be archived.
