### ISSUE TITLE
After initial registration in OSIAM, boolean values are shown as 'true' although they are 'false'

### ISSUE THREAD

**Issue by ckoeni** [osiam/addon-administration#83]
After the initial registration in OSIAM the 'edit User' view is shown. All checkboxes are marked as 'true' but the boolean values are not stored in the database. If I uncheck these boxes and activate 'save' the boolean values are still shown as 'true' after reloading.

**Comment by tkrille** [comment]
Hello @ckoeni,

I assume, that this is an issue with boolean-typed extension fields. Is this right? What version of addon-administration are you using?

**Comment by tkrille** [comment]
@ckoeni I need more information on this. Please help me out here.

**Comment by ckoeni** [comment]
Hello @tkrille,

we are using the latest version of the addon-administration (1.6) and the issue is related to boolean-typed extension fields.

**Comment by tkrille** [comment]
@ckoeni Accepted as bug and already solved. This is scheduled for 2.0 now. If you need this earlier than 2.0 will be released, just let me know and we can incorporate this fix into a 1.x maintenance version.
